server:
  port: 10001
  servlet:
    context-path: /api
    session:
      timeout: 7200s

spring:
  application:
    name: petHome-mobile-bff

  # consul
  cloud:
    consul:
      discovery:
        health-check-path: ${server.servlet.context-path}/health  # 检测实例健康
        health-check-interval: 10s   # 每隔10s检查
        hostname: localhost    # 配置实例地址
        register: true  # 自动注册
        service-name: ${spring.application.name} # 实例名称
        instanceId: ${spring.application.name}:${server.port}:${random.value}:${random.int[1,1000000]}
        prefer-ip-address: true
      host: localhost
      port: 8500



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: 爱宠回家
  application-version: 1.0
  application-description: 爱宠回家移动端接口文档
  try-host: http://localhost:${server.port}
